services:
  - type: web
    name: optimizer-wordle
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: optimizer-wordle-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false

databases:
  - name: optimizer-wordle-db
    plan: starter
    databaseName: optimizer_wordle
    user: optimizer_wordle_user
