services:
  - type: web
    name: optimizer-wordle
    env: node
    plan: free
    buildCommand: NODE_ENV=development npm install && npx prisma generate && NODE_ENV=production npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: optimizer-wordle-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: optimizer-wordle
          property: url

databases:
  - name: optimizer-wordle-db
    plan: free
    databaseName: optimizer_wordle
    user: optimizer_wordle_user
